classDiagram
    IPhone <|-- ReprodutorMusical
    IPhone <|-- AparelhoTelefonico
    IPhone <|-- NavegadorInternet
    IPhone : +tocar()
    IPhone : +pausar()
    IPhone : +selecionarMusica(String musica)
    IPhone : +ligar(String numero)
    IPhone : +atender()
    IPhone : +iniciarCorreioVoz()
    IPhone : +exibirPagina(String url)
    IPhone : +adicionarNovaAba()
    IPhone : +atualizarPagina()
     class ReprodutorMusical
     <<interface>> ReprodutorMusical
     ReprodutorMusical : +tocar()
     ReprodutorMusical : +pausar()
     ReprodutorMusical : +selecionarMusica(String musica)

    class AparelhoTelefonico
    <<interface>> AparelhoTelefonico
    AparelhoTelefonico : +ligar(String numero)
    AparelhoTelefonico : +atender()
    AparelhoTelefonico : +iniciarCorreioVoz()

    class NavegadorInternet
    <<interface>> NavegadorInternet
    NavegadorInternet : +exibirPagina(String url)
    NavegadorInternet : +adicionarNovaAba()
    NavegadorInternet : +atualizarPagina()
    


